#!/bin/sh


file=`./uniquefile.exe`
if test -z "$file"
then
    exit 0
fi
# dup=$(echo $file | tr ";" "\n")

while IFS=';' read -ra ADDR;
do 
    for i in "${ADDR[@]}";
    do 
        echo "> [$i]"
    done
done <<< "$file"
exit 1